### ISSUE TITLE
Is it possible to just get the bare score as a number 0 to 100 for automated use?

### ISSUE THREAD

**Issue by DamonHD** [Heydon/readabilityCheckerCLI#3]
There seems to be control codes etc embedded in the output: a command-line option to just get get the score, eg for automated tools to reject bad copy before it goes up on the Web, would be great.

(Thanks for the tool, BTW!)

Rgds

Damon

**Comment by Heydon** [comment]
@DamonHD That's a great idea. I'm not actively developing this but I may create a new version that integrates that feature.

**Comment by DamonHD** [comment]
Any progress?  Was just thinking about this again today!

Rgds

Damon

**Comment by Heydon** [comment]
@DamonHD I'm sorry, no. I've not had time to completely rebuild this tool.

**Comment by DamonHD** [comment]
No problem, I have found another way to get what I needed.

Thanks again for your work, which set me on the right path!

Rgds

Damon

**Comment by Heydon** [comment]
@DamonHD Cool!
